import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#f5f5f5",
    flex: 1,
    alignSelf: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
  },
  searchView: {
    height: 40,
    paddingHorizontal: 20,
    paddingTop: 10,
    flexDirection: "row",
    width: "100%",
    backgroundColor: "#fff",
    height: 65,
  },
  searchImg: {
    width: 20,
    height: 20,
    resizeMode: "contain",
    marginTop: 15,
  },
  searchBar: {
    marginLeft: 15,
    marginTop: 5,
    width: "100%",
    borderWidth: 0,
    height: 40,
    justifyContent: "center",
  },
  backArrow: {
    width: "20%",
    height: "10%",
    marginHorizontal: 20,
    paddingTop: 10,
  },
  loginText: {
    fontFamily: "SF-SemiBold",
    fontSize: 22,
    fontWeight: "600",
    alignSelf: "center",
    color: "#060606",
  },
  userSignup: {
    width: "100%",
    height: 70,
    justifyContent: "center",
    textAlign: "center",
    borderBottomWidth: 0.5,
    borderBottomColor: "#cecece",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  user: {
    // justifyContent: "space-between",
    textAlign: "center",
    justifyContent: "center",
  },
  listTitle: {
    fontFamily: "SF-SemiBold",
    fontSize: 22,
  },
  listDescription: {
    fontFamily: "SF-SemiBold",
    fontSize: 12,
    marginLeft: 20,
  },
  title: {
    fontFamily: "SF-SemiBold",
    fontSize: 18,
    color: "#333",
    width: "40%",
    marginLeft: 20,
  },
  item: {
    padding: 20,
    marginVertical: 0,
    marginHorizontal: 0,
    flex: 1,
    flexDirection: "row",
    borderColor: "#738388",
    borderTopWidth: 0.5,
    alignItems: "center",
  },
  fabView: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    backgroundColor: "#FF2632",
    bottom: "12%",
    right: 24,
    zIndex: 2,
    shadowOffset: { width: 0, height: 2 },
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
