import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  section: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "#F7F8FA",
    borderTopWidth: 1,
    borderTopColor: "#cecece",
    width: "100%",
    height: 40,
    paddingHorizontal: 20,
  },
  backBtn: {
    width: 25,
    height: 25,
    resizeMode: "contain",
  },
  searchView: {
    flexDirection: "row",
    width: "100%",
    height: 80,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  search: {
    marginLeft: 15,
    marginTop: 5,
    width: "100%",
    borderWidth: 0,
    height: 40,
    justifyContent: "center",
  },
  sectionText: {
    paddingLeft: 10,
    fontWeight: "bold",
    fontFamily: "SF-SemiBold",
    fontSize: 16,
    paddingVertical: 10,
  },
  item: {
    padding: 20,
    marginVertical: 0,
    marginHorizontal: 0,
    flex: 1,
    flexDirection: "row",
    borderColor: "#cecece",
    borderTopWidth: 0.5,
    alignItems: "center",
  },
  title: {
    fontFamily: "SF-SemiBold",
    fontSize: 16,
    color: "#000000",
    fontWeight: "bold",
    width: "100%",
    marginLeft: 15,
  },
  title1: {
    fontFamily: "SF-SemiBold",
    fontSize: 14,
    color: "#738388",
    width: "100%",
    marginLeft: 15,
  },
  container: {
    flex: 1,
    alignSelf: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    backgroundColor: "#ffffff",
  },
  halfScreen: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    borderColor: "red",
  },
});
