import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  mainView: { width: "100%", height: "100%" },
  backBtn: {
    height: "100%",
    width: 50,
    justifyContent: "center",
  },
  searchView: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
  },
  searchImage: {
    marginVertical: 12,
    width: 22,
    height: 32,
    resizeMode: "contain",
  },
  search: {
    marginLeft: 15,
    marginTop: 5,
    width: "70%",
    borderWidth: 0,
    height: "100%",
  },
  titleView: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  ratingView: {
    width: "100%",
    height: "30%",
    borderEndWidth: 0,
    justifyContent: "center",
  },
  ratingBg: {
    width: "100%",
    height: "80%",
    borderEndWidth: 0.5,
  },
  ratingStars: {
    width: "90%",
    borderRadius: 7,
    borderWidth: 0.5,
    height: "70%",
    borderColor: "#B7BDBF",
    backgroundColor: "#F9F9F9",
    alignSelf: "center",
    justifyContent: "center",
  },
  ratingView2: {
    width: "100%",
    alignItems: "center",
  },
  headTitle: {
    fontFamily: "SF-SemiBold",
    fontSize: 22,
    fontWeight: "600",
    alignSelf: "center",
    color: "#060606",
  },
  resetBtn: {
    width: "18%",
    height: "50%",
    borderRadius: 5,
    borderColor: "#D6D6D6",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  btnText: { fontFamily: "SF-SemiBold", fontSize: 15, alignSelf: "center" },
  netPic: {
    width: 75,
    height: 70,
  },
  itemView: {
    flex: 1,
    flexDirection: "row",
    marginBottom: 10,
    width: "100%",
    marginRight: 10,
  },
  item: {
    width: "100%",
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  availableonTextBox: {
    width: "100%",
    height: 60,
    justifyContent: "center",
  },
  availableonNetflix: {
    width: "100%",
    height: "65%",
  },
  category: {
    width: "100%",
    flexDirection: "row",
  },
  backArrow: {
    width: "100%",
    height: 70,
    backgroundColor: "white",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    borderBottomColor: "#D6D6D6",
    borderBottomWidth: 0.5,
    paddingHorizontal: 15,
  },
  backArrowHead: {
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    width: "100%",
    height: 70,
    textAlign: "center",
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#cecece",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  starRatingBox: {
    width: "100%",
    height: 170,
    borderBottomColor: "#D6D6D6",
    borderBottomWidth: 0.5,
  },
  avialableOnBox: {
    width: "100%",
    height: 150,
    backgroundColor: "white",
    borderBottomColor: "#D6D6D6",
    borderBottomWidth: 0.5,
    paddingHorizontal: 15,
  },
  avialableOnBox2: {
    width: "100%",
    backgroundColor: "white",
    borderBottomColor: "#D6D6D6",
    paddingHorizontal: 15,
  },
  container: {
    flex: 1,
    alignSelf: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    backgroundColor: "#fff",
  },
  smText2: {
    fontFamily: "SF-SemiBold",
    fontSize: 19,
    fontWeight: "500",
    alignSelf: "center",
  },
  smText22: {
    fontFamily: "SF-SemiBold",
    fontSize: 19,
    fontWeight: "500",
    alignSelf: "flex-start",
    paddingHorizontal: 15,
  },
  searchText: {
    color: "white",
    fontFamily: "SF-SemiBold",
    fontSize: 19,
    fontWeight: "700",
    alignSelf: "center",
  },
  availableText: {
    fontFamily: "SF-SemiBold",
    fontSize: 19,
    fontWeight: "500",
  },
  btnView: {
    width: "100%",
    marginBottom: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  btnSearch: {
    width: "88%",
    borderRadius: 7,
    height: 50,
    backgroundColor: "#FF2632",
    justifyContent: "center",
    alignItems: "center",
  },
});
