import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    countryContainer: {
        marginVertical: 15,
      },
      mainView: {
        width: "100%",
        height: "100%",
        justifyContent: "center",
        alignItems: "center",
      },
      uploaderView: {
        width: 150,
        height: 150,
        resizeMode: "contain",
        alignItems: "center",
        alignSelf: "center",
        justifyContent: "center",
        borderWidth: 3,
        borderColor: "#738388",
        borderRadius: 80,
      },
      profileView: {
        width: 150,
        height: 150,
        borderRadius: 80,
        resizeMode: "cover",
        alignItems: "center",
        alignSelf: "center",
      },
      coverImage: {
        width: 35,
        height: 35,
        borderWidth: 2,
        borderRadius: 17.5,
        borderColor: "#263438",
        justifyContent: "center",
        backgroundColor: "#738388",
        position: "absolute",
        alignSelf: "flex-end",
        bottom: 1,
      },
      uploadCover: {
        width: "90%",
        margin: 30,
        alignSelf: "center",
        borderColor: "#738388",
        borderStyle: "dashed",
        borderWidth: 1,
        borderRadius: 5,
      },
      flag: {
        flex: 1,
        marginRight: 10,
        flexDirection: "row",
      },
      flagText: {
        color: "white",
      },
      coverImageView: {
        marginVertical: 10,
        marginHorizontal: 5,
        backgroundColor: "#738388",
        justifyContent: "center",
        alignSelf: "center",
        width: "95%",
        height: 120,
      },
      coverIcon: {
        width: "50%",
        height: "50%",
        resizeMode: "contain",
        alignItems: "center",
        alignSelf: "center",
      },
      uploadText: {
        color: "#fff",
        fontFamily: "SF-Regular",
        fontSize: 20,
        paddingTop: 10,
        textAlign: "center",
        marginBottom: 20,
      },
      placeholderBox1: {
        width: "70%",
        height: 50,
        borderWidth: 0,
        borderColor: "white",
        color: "white",
        paddingHorizontal: 15,
        fontFamily: "SF-Regular",
        fontSize: 18,
      },
      radioBtnStyle1: {
        flexDirection: "row",
        alignItems: "center",
        marginRight: 40,
      },
      radioTxtStyle1: {
        justifyContent: "center",
        textAlign: "center",
        marginLeft: 13,
        fontFamily: "SF-Regular",
        fontSize: 18,
        color: "white",
      },
      user: {
        flex: 1,
        alignSelf: "flex-end",
        justifyContent: "flex-end",
        flexDirection: "row",
      },
      btnText: {
        width: "90%",
        height: 50,
        marginTop: 12,
        backgroundColor: "#FF2632",
        justifyContent: "center",
        borderRadius: 8,
        marginBottom: 20,
      },
      lableStyle: {
        color: "white",
        fontFamily: "SF-Regular",
        fontSize: 18,
        marginRight: -10,
        textDecorationLine: "underline",
      },
      lableView: {
        width: "90%",
        height: 40,
        marginBottom: 10,
        justifyContent: "flex-end",
        alignItems: "flex-end",
      },
      lableStyle1: {
        color: "white",
        fontSize: 18,
        fontFamily: "SF-Regular",
        marginLeft: 25,
      },
      lableView1: {
        width: "50%",
        height: 5,
        justifyContent: "flex-start",
        alignItems: "flex-start",
      },
      placeholderTop: {
        width: "100%",
        marginBottom: 5,
        fontFamily: "SF-Regular",
        height: 20,
        justifyContent: "center",
      },
      placeholderTopText: {
        color: "white",
        fontSize: 18,
        fontFamily: "SF-Regular",
      },
      placeholderBox: {
        width: "100%",
        height: 50,
        color: "#fff",
        fontSize: 18,
        borderRadius: 5,
        borderWidth: 0.5,
        borderColor: "white",
        paddingHorizontal: 15,
        fontFamily: "SF-Regular",
      },
      emailWholeBox: {
        width: "90%",
        alignSelf: "center",
        height: 80,
        marginTop: 20,
        color: "#fff",
        borderColor: "blue",
      },
      countryPickerView: {
        height: 50,
        flexDirection: "row",
        justifyContent: "center",
        borderRadius: 5,
        borderWidth: 0.5,
        borderColor: "white",
      },
      radiobtnBox: {
        width: "100%",
        height: 40,
        borderRadius: 7,
        flexDirection: "row",
        paddingLeft: 7,
      },
      loginText: {
        fontFamily: "SF-Regular",
        fontSize: 43,
        color: "white",
        flex: 1,
        alignSelf: "center",
        flexDirection: "row",
      },
      backArrow: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "flex-start",
        alignItems: "flex-start",
        alignSelf: "flex-start",
        paddingHorizontal: 20,
        paddingVertical: 20,
      },
      userSignup: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        marginBottom: 20,
      },
      container: {
        flex: 1,
      },
      halfScreen: {
        flex: 1,
      },
      View1: {
        flex: 1,
        width: "100%",
        flexDirection: "column",
        paddingVertical: 20,
      },
      btnText2: {
        fontFamily: "SF-Regular",
        fontSize: 22,
        color: "#fff",
        alignSelf: "center",
        justifyContent: "center",
      },
      eyeIcon: {
        position: "relative",
        top: -38,
        right: 10,
        alignSelf: "flex-end",
      },
      imageStyle: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
      },
      btnView: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        marginVertical: 10,
        padding: 10,
      },
});
