import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    socialBtn: {
        width: "95%",
        height: "20%",
        marginTop: 12,
        backgroundColor: "#3b5998",
        borderRadius: 6,
        marginBottom: 20,
        flexDirection: "row",
        flex: 1,
      },
      smTextbtn: {
        color: "white",
        fontFamily: "SF-Regular",
        fontSize: 20,
        textAlign: "center",
      },
      container: {
        flex: 1,
        alignSelf: "center",
        justifyContent: "space-between",
        width: "100%",
        height: "100%",
        backgroundColor: "black",
      },
      halfScreen: {
        width: "100%",
        height: "55%",
        marginBottom: "2%",
        justifyContent: "flex-end",
        alignItems: "center",
      },
      smText: {
        color: "white",
        fontFamily: "SF-SemiBold",
        fontSize: 28,
        marginTop: 20,
      },
      smText2: {
        color: "white",
        fontFamily: "SF-Regular",
        fontSize: 20,
        alignSelf: "center",
      },
      smText3: {
        color: "white",
        fontFamily: "SF-Regular",
        fontSize: 18,
        alignSelf: "center",
      },
      lgText: {
        color: "white",
        fontFamily: "SF-SemiBold",
        fontSize: 55,
      },
      lowerHalfScreen: {
        width: "95%",
        alignSelf: "center",
        paddingTop: 20,
        height: "40%",
        alignItems: "center",
      },
      block: {
        width: "95%",
        height: 60,
        borderWidth: 4,
        borderColor: "transparent",
        borderRadius: 7,
        marginTop: 9,
      },
      block2: {
        width: "93%",
        height: "17%",
        borderWidth: 1,
        borderColor: "white",
        alignItems: "center",
        borderRadius: 7,
        marginTop: 13,
        justifyContent: "center",
      },
      block3: {
        width: "95%",
        height: "20%",
        borderColor: "white",
        borderRadius: 7,
        marginTop: 20,
        justifyContent: "center",
      },
      fbImage: {
        width: "20%",
        height: "50%",
        resizeMode: "contain",
        marginVertical: 12,
        paddingHorizontal: 35,
        justifyContent: "center",
      },
      imageStyle: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
      },
});
