import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  movieBoxView: {
    marginTop: 10,
    width: "100%",
    borderRadius: 7,
    borderColor: "white",
    backgroundColor: "white",
    padding: 10,
  },
  backArrow: {
    width: "100%",
    height: 70,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 10,
    width: "100%",
    height: 70,
    textAlign: "center",
    borderBottomWidth: 0,
    borderBottomColor: "#cecece",
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#cecece",
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  container: {
    flex: 1,
    alignSelf: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    backgroundColor: "black",
  },
  halfScreen: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    borderColor: "red",
  },
  imageStyle: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  screenTitle: {
    fontFamily: "SF-SemiBold",
    fontSize: 22,
    fontWeight: "600",
    alignSelf: "center",
    color: "#060606",
  },
  item: {
    paddingTop: 10,
    padding: 10,
    marginVertical: 0,
    marginHorizontal: 0,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  item1: {
    padding: 10,
    marginVertical: 0,
    marginHorizontal: 0,
    // flex: 1,
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#738388",
    borderWidth: 0.5,
  },
  title: {
    fontSize: 18,
    color: "#000000",
    width: "100%",
    fontWeight: "900",
  },
});
