import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  PostButton: {
    width: "15%",
    height: "50%",
    borderRadius: 4,
    borderColor: "#D6D6D6",
    right: 20,
    borderWidth: 1,
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(11, 21, 23, 0.8)",
    justifyContent: "center",
  },
  ratingView: {
    width: "90%",
    height: 230,
    borderColor: "#D6D6D6",
    padding: 10,
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "white",
    borderRadius: 7,
  },
  ratingStarsView: {
    width: "100%",
    height: "20%",
    borderEndWidth: 0,
    justifyContent: "center",
    alignItems: "center",
  },
  ratingStars: {
    width: "100%",
    height: "20%",
    borderEndWidth: 0,
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "SF-Regular",
  },
  box: {
    width: "100%",
    height: 70,
    backgroundColor: "white",
    borderTopWidth: 1,
    borderTopColor: "#D6D6D6",
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  box1: {
    width: "100%",
    height: 70,
    borderTopWidth: 1,
    borderTopColor: "#D6D6D6",
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FF2632",
    opacity: 0.9,
  },

  textInsideBox1: {
    fontFamily: "SF-SemiBold",
    fontSize: 14,
  },

  textInsideBox2: {
    fontFamily: "SF-SemiBold",
    fontSize: 14,
    color: "#fff",
  },
  backArrow2: {
    flex: 1,
    height: 70,
    backgroundColor: "#fff",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    borderBottomColor: "#D6D6D6",
    borderBottomWidth: 0.5,
    paddingHorizontal: 15,
  },
  picImage: {
    width: 45,
    height: 45,
  },
  pic: {
    width: "15%",
    height: "100%",
    justifyContent: "center",
  },
  postUserName: {
    fontFamily: "SF-SemiBold",
    fontSize: 16,
    fontWeight: "bold",
  },
  reviewBox: {
    width: "100%",
    padding: 15,
    fontSize: 18,
    color: "#000",
    fontFamily: "SF-Regular",
    backgroundColor: "white",
    height: 250,
    textAlignVertical: 'top',
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  smText2: {
    fontFamily: "heading",
    fontSize: 30,
    alignSelf: "center",
  },
  smText3: {
    fontFamily: "SF-SemiBold",
    fontSize: 18,
    alignSelf: "center",
  },
  imageStyle: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
});
