import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  innerCont: {
    width: "100%",
    height: "100%",
    backgroundColor: "white",
  },
  followBtn: {
    width: 120,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 6,
    borderWidth: 0.6,
    borderColor: "white",
    paddingVertical: 4,
    paddingHorizontal: 8,
    margin: 15,
  },
  myProfileView: {
    flex: 1,
    justifyContent: "flex-end",
    alignContent: "flex-end",
    alignItems: "center",
    // bottom: 4,
  },
  myImg: {
    width: 140,
    height: 140,
    resizeMode: "contain",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 10,
  },
  editView: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginHorizontal: 10,
    position: "absolute",
    alignSelf: "flex-end",
    bottom: 0,
  },
  editImg: {
    width: 50,
    height: 50,
    resizeMode: "contain",
    alignItems: "center",
    alignSelf: "center",
  },
  editSec: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  horizontalImg: {
    width: 120,
    height: 180,
    resizeMode: "contain",
    alignItems: "center",
    alignSelf: "center",
    //color:"white"
    marginLeft: 10,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
  },
  midBarView: {
    height: 70,
    width: "100%",
    backgroundColor: "#738388",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  midBarCont: {
    flex: 1,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  midBarTxt: {
    color: "white",
    fontFamily: "SF-Regular",
    marginTop: 3,
    fontSize: 16,
  },
  midBarNo: { color: "white", fontFamily: "SF-Regular" },
  GenreView: {
    // padding: 5,
    height: 125,
    width: 110,
    backgroundColor: "#2A363A",
    opacity: 0.8,
    marginHorizontal: 5,
    // paddingBottom: 20,
    alignItems: "center",
  },
  aboutView: {
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderBottomColor: "#738388",
    borderBottomWidth: 0.2,
    backgroundColor: "#0C1A1E",
  },
  about: {
    padding: 10,
    textAlign: "justify",
    fontFamily: "SF-Light",
    fontSize: 18,
    color: "#fff",
    paddingBottom: 20,
    width: "98%",
  },
  heading: {
    paddingTop: 10,
    paddingLeft: 10,
    fontFamily: "SF-SemiBold",
    fontSize: 18,
    color: "#fff",
  },
  movieBoxView: {
    marginTop: 10,
    width: "100%",
    borderRadius: 7,
    borderColor: "white",
    backgroundColor: "white",
    padding: 10,
  },
  imageStyle: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  tabBar: {
    flexDirection: "row",
  },
  name1: {
    padding: 2,
    paddingVertical: 10,
    color: "#fff",
    fontFamily: "SF-Light",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    justifyContent: "center",
  },
  name: {
    padding: 2,
    color: "#fff",
    fontFamily: "SF-Light",
    justifyContent: "center",
    fontSize: 18,
    textAlign: "center",
  },
  imageStyle: { width: "100%", height: "100%", resizeMode: "cover" },
  photosView: {
    width: "100%",
    height: "100%",
  },
  wholeViewForReviews: {
    width: "95%",
    height: "100%",
    alignSelf: "center",
  },
  ScrollView: { width: "95%", alignSelf: "center" },
  container: {
    alignSelf: "center",
    width: "100%",
    height: "100%",
  },
  arrow: {
    justifyContent: "flex-start",
  },
  mainTop: {
    width: "100%",
    // height: "29%",
    height: 280,
  },
  aboutWholeView: {
    width: "100%",
    // height: "7%",
    height: 60,
    borderBottomWidth: 1,
    borderBottomColor: "#738388",
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-around",
  },
  aboutTagSelected: {
    //width: "30%",
    height: "100%",
    borderBottomWidth: 3,
    marginTop: 2,
    borderBottomColor: "#FF2632",
    justifyContent: "center",
    alignItems: "center",
  },
  aboutTag: {
    //width: "27%",
    height: "100%",
    borderBottomWidth: 3,
    marginTop: 2,
    borderBottomColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
  },

  aboutTextSelected: {
    fontSize: 20,
    //fontWeight: "700",
    fontFamily: "SF-SemiBold",
    color: "#fff",
    alignSelf: "center",
  },
  aboutText: {
    fontSize: 20,
    //fontWeight: "700",
    fontFamily: "SF-SemiBold",
    color: "#fff",
    alignSelf: "center",
  },

  item: {
    paddingTop: 10,
    padding: 10,
    marginVertical: 0,
    marginHorizontal: 0,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  item1: {
    padding: 10,
    marginVertical: 0,
    marginHorizontal: 0,

    flexDirection: "row",
    alignItems: "center",
    borderColor: "#738388",
    borderWidth: 0.5,
  },
  title: {
    fontSize: 18,
    color: "#000000",
    width: "100%",
    fontWeight: "900",
  },
});
