import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  radioBtnStyle1: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 40,
  },
  ScrollPortion: {
    flex: 3,
    flexDirection: "column",
    width: "100%",
  },
  radioTxtStyle1: {
    justifyContent: "center",
    textAlign: "center",
    marginLeft: 12,
    fontFamily: "SF-Regular",
    fontSize: 18,
    color: "white",
  },
  user: {
    flex: 1,
    flexDirection: "row",
  },
  userImage: {
    width: 84,
    height: 84,
    borderWidth: 2,
    borderColor: "grey",
    resizeMode: "contain",
    borderRadius: 42,
  },
  userImage2: {
    width: 81,
    height: 81,
    borderColor: "grey",
    resizeMode: "cover",
    borderRadius: 40.5,
  },

  uploadImage: {
    flex: 1,
    alignSelf: "flex-end",
    justifyContent: "flex-end",
    width: 20,
    height: 20,
    right: 12,
    bottom: 0,
    resizeMode: "contain",
    position: "absolute",
  },
  uploadImage2: {
    flex: 1,
    alignSelf: "flex-end",
    justifyContent: "flex-end",
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  loginBtn: {
    width: "90%",
    height: 50,
    marginTop: 12,
    backgroundColor: "#FF2632",
    justifyContent: "center",
    borderRadius: 8,
    marginBottom: 20,
  },
  smText2: {
    fontFamily: "SF-Regular",
    fontSize: 22,
    color: "#fff",
    alignSelf: "center",
    justifyContent: "center",
  },
  forgotText: {
    color: "white",
    fontFamily: "SF-SemiBold",
    fontSize: 15,
  },
  forgot: {
    width: "90%",
    height: "8%",
    //backgroundColor:"blue",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },

  placeholderTop: {
    width: "100%",
    height: 30,
    justifyContent: "center",
  },
  placeholderTopText: {
    color: "white",
    fontSize: 18,
    fontFamily: "SF-Regular",
  },
  placeholderBox: {
    width: "100%",
    height: 50,
    color: "#fff",
    fontSize: 18,
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: "white",
    paddingHorizontal: 15,
    fontFamily: "SF-Regular",
  },
  placeholderBox1: {
    width: "70%",
    height: 50,
    borderWidth: 0,
    borderColor: "white",
    color: "white",
    paddingHorizontal: 15,
    fontFamily: "SF-Regular",
    fontSize: 18,
  },
  radiobtnBox: {
    width: "100%",
    height: 80,
    borderRadius: 7,
    flexDirection: "row",
    paddingLeft: 7,
  },
  emailWholeBox: {
    marginTop: 20,
    width: "90%",
    alignSelf: "center",
    height: 80,
  },
  loginText: {
    fontFamily: "SF-Regular",
    fontSize: 43,
    color: "white",
    flex: 1,
    alignSelf: "center",
    flexDirection: "row",
  },
  backArrow: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    alignSelf: "flex-start",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  userSignup: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  //xxxxxxxxx
  container: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "black",
  },

  halfScreen: {
    width: "100%",
    height: "100%",
    flexDirection: "column",
    flex: 1,
  },
  View1: {
    flex: 1,
    width: "100%",
    flexDirection: "column",
    paddingVertical: 20,
  },
  done: {
    width: 30,
    height: 35,
    backgroundColor: "#FF2632",
    borderRadius: 20,
    justifyContent: "center",
  },
  imageStyle: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    backgroundColor: "#122024",
  },
  eyeIcon: {
    position: "relative",
    top: -38,
    right: 10,
    alignSelf: "flex-end",
  },
  countryContainer: {
    height: 50,
    borderWidth: 0,
    borderColor: "white",
    color: "white",
    paddingHorizontal: 15,
    fontFamily: "SF-Regular",
    fontSize: 18,
  },

  flag: {
    flex: 1,
    flexDirection: "row",
  },
  flagText: {
    marginVertical: 12,
    paddingRight: 5,
    height: 50,
    borderWidth: 0,
    borderColor: "white",
    color: "white",
    fontFamily: "SF-Regular",
    fontSize: 18,
  },
});
