import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  placeholderBox: {
    width: "100%",
    height: 50,
    color: "#fff",
    fontSize: 18,
    borderRadius: 5,
    borderWidth: 0.5,
    borderColor: "white",
    paddingHorizontal: 15,
    fontFamily: "SF-Regular",
  },
  loginBtn: {
    width: "90%",
    height: 50,
    marginTop: 12,
    backgroundColor: "#FF2632",
    justifyContent: "center",
    borderRadius: 8,
    marginBottom: 20,
    marginTop: 30,
  },
  placeholderTop: {
    width: "100%",
    height: 30,
    justifyContent: "center",
  },
  placeholderTopText: {
    color: "white",
    fontSize: 18,
    fontFamily: "SF-Regular",
  },
  emailWholeBox: {
    marginTop: 20,
    width: "90%",
    alignSelf: "center",
    height: 80,
  },
  container: {
    flex: 1,
    alignSelf: "center",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    backgroundColor: "black",
  },
  halfScreen: {
    width: "100%",
    height: "60%",
    alignItems: "center",
    borderColor: "red",
  },
  btnText: {
    color: "white",
    fontFamily: "SF-SemiBold",
    fontSize: 18,
    fontWeight: "bold",
    alignSelf: "center",
  },
  userImage: {
    width: 65,
    height: 65,
    resizeMode: "stretch",
    borderRadius: 7,
    alignSelf: "center",
  },
  eyeIcon: {
    position: "relative",
    top: -38,
    right: 10,
    alignSelf: "flex-end",
  },
  imageStyle: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
});
